#!/usr/bin/env python3
"""
Escritor v2.0 - Story Agent
Full tool access, Ollama for writing assistance
"""

import sys
sys.path.insert(0, '/home/chad-yi/.openclaw/workspace/infrastructure')

from agent_client import AgentClient
import json
import logging
from datetime import datetime
import asyncio

logging.basicConfig(level=logging.INFO)
logger = logging.getLogger(__name__)

class EscritorAgent:
    def __init__(self):
        self.client = AgentClient('escritor')
        self.base_dir = '/home/chad-yi/.openclaw/workspace/agents/escritor'
        self.inbox_dir = f'{self.base_dir}/inbox'
        self.outbox_dir = f'{self.base_dir}/outbox'
        self.projects_dir = f'{self.base_dir}/projects'
        
    async def run(self):
        """Main agent loop"""
        logger.info("=" * 50)
        logger.info("ESCRITOR v2.0 - Story Agent Starting")
        logger.info("=" * 50)
        
        await self.client.connect()
        logger.info("Connected to hub")
        
        while True:
            await self.process_tasks()
            await asyncio.sleep(300)  # Check every 5 minutes
    
    async def process_tasks(self):
        """Check inbox and process writing tasks"""
        import glob
        
        task_files = glob.glob(f'{self.inbox_dir}/TASK-*.md')
        
        if not task_files:
            return
            
        logger.info(f"Found {len(task_files)} task(s)")
        
        for task_file in sorted(task_files, key=os.path.getmtime):
            task_name = os.path.basename(task_file)
            logger.info(f"Processing: {task_name}")
            
            # Read task
            result = self.client.file_read(f'agents/escritor/inbox/{task_name}')
            if 'error' in result:
                continue
            
            task_content = result['content']
            
            # Process based on task type
            if 'CHAPTER' in task_name.upper():
                await self.write_chapter(task_name, task_content)
            elif 'STUDY' in task_name.upper() or 'ANALYSIS' in task_name.upper():
                await self.analyze_story(task_name, task_content)
            else:
                await self.generic_response(task_name, task_content)
    
    async def write_chapter(self, task_name, task_content):
        """Write a story chapter using Ollama"""
        logger.info(f"Writing chapter for: {task_name}")
        
        # Read story bible for context
        bible_result = self.client.file_read('projects/A2-reunite/STORY-BIBLE-CORRECTED.md')
        story_bible = bible_result.get('content', '')[:5000] if 'content' in bible_result else ''
        
        # Use Ollama to generate chapter
        prompt = f"""You are a professional fiction writer. Write a chapter for RE:UNITE novel.

Story Bible Context:
{story_bible}

Task:
{task_content}

Write approximately 2000 words. Focus on character development and advancing the plot."""

        # Call Ollama
        result = self.client.exec(
            f'curl -s http://localhost:11434/api/generate -d \'{{"model": "qwen2.5:7b", "prompt": {json.dumps(prompt)}, "stream": false}}\'',
            timeout=300
        )
        
        try:
            response = json.loads(result.get('stdout', '{}'))
            chapter_text = response.get('response', 'Error: No response from Ollama')
        except:
            chapter_text = f"Error generating chapter: {result.get('stderr', 'Unknown error')}"
        
        # Write chapter to file
        timestamp = datetime.now().strftime('%Y%m%d-%H%M')
        chapter_file = f'agents/escritor/projects/chapter-{timestamp}.md'
        
        content = f"""# Chapter Draft - {timestamp}
**Generated by Escritor v2.0**

{chapter_text}

---
*Note: This is a draft. Review and edit as needed.*
"""
        
        result = self.client.file_write(chapter_file, content)
        
        if result.get('success'):
            logger.info(f"✅ Chapter written to {chapter_file}")
            
            # Notify via WebSocket
            await self.client.broadcast('chapter_complete', {
                'file': chapter_file,
                'word_count': len(chapter_text.split())
            })
        else:
            logger.error(f"Failed to write chapter: {result}")
    
    async def analyze_story(self, task_name, task_content):
        """Analyze story elements"""
        logger.info(f"Analyzing story: {task_name}")
        
        # Read existing chapters
        chapters_result = self.client.exec('ls ~/.openclaw/workspace/temp-reunite/*.txt 2>/dev/null | head -5')
        chapters = chapters_result.get('stdout', '').strip().split('\n')[:3]
        
        analysis = f"""# Story Analysis - {datetime.now().isoformat()}
**Generated by Escritor v2.0**

## Available Chapters
{chr(10).join([f"- {c}" for c in chapters if c])}

## Analysis
Based on the RE:UNITE story bible and existing chapters:

### Key Characters
- Markus Chen (protagonist)
- Various district representatives
- Tournament contenders

### Current Plot Points
- Individual trials completed
- Contender tournament ongoing
- World-building through magic system

### Next Chapter Recommendations
1. Continue contender tournament progression
2. Develop character relationships
3. Advance political intrigue

## Task Response
{task_content[:500]}...

---
*Ready to write next chapter on request.*
"""
        
        timestamp = datetime.now().strftime('%Y%m%d-%H%M')
        result = self.client.file_write(
            f'agents/escritor/outbox/analysis-{timestamp}.md',
            analysis
        )
        
        if result.get('success'):
            logger.info(f"✅ Analysis written")
    
    async def generic_response(self, task_name, task_content):
        """Generic response"""
        response = f"""# Escritor Response: {task_name}
**Received:** {datetime.now().isoformat()}

I received your task. I'm currently configured to:
- Write story chapters using Ollama (qwen2.5:7b)
- Analyze story structure and characters
- Provide writing recommendations

Please specify what you'd like me to write or analyze.

## Current Status
- Model: qwen2.5:7b (Ollama)
- Story Bible: Loaded
- Available chapters: 1-12
"""
        
        timestamp = datetime.now().strftime('%Y%m%d-%H%M')
        self.client.file_write(
            f'agents/escritor/outbox/response-{timestamp}.md',
            response
        )
        logger.info(f"✅ Generic response sent")

if __name__ == '__main__':
    import os
    agent = EscritorAgent()
    asyncio.run(agent.run())
