#!/bin/bash
# Setup Kimi-Claw-Helios on kimi.com

echo "=============================================="
echo "Kimi-Claw-Helios Setup Guide"
echo "New Helios with Browser Automation"
echo "=============================================="
echo ""

echo "STEP 1: Create Kimi Claw Instance"
echo "-----------------------------------"
echo "1. Go to: https://www.kimi.com/bot"
echo "2. Click 'Create Kimi Claw'"
echo "3. Name: 'Kimi-Claw-Helios'"
echo "4. Click Deploy"
echo ""

echo "STEP 2: Install Skills"
echo "----------------------"
echo "In Kimi Claw terminal, run:"
echo ""
echo "clawhub install screenshot"
echo "clawhub install browser"
echo "clawhub install system-monitor"
echo "clawhub install telegram"
echo "clawhub install cron"
echo ""

echo "STEP 3: Copy Config Files"
echo "-------------------------"
echo "Copy these files to Kimi Claw workspace:"
echo ""
echo "1. SKILL.md → ~/skills/kimi-claw-helios/SKILL.md"
echo "2. HEARTBEAT.md → ~/HEARTBEAT.md"
echo "3. TELEGRAM_CONFIG.md → ~/TELEGRAM_CONFIG.md"
echo ""

echo "STEP 4: Login to Telegram Web"
echo "-----------------------------"
echo "1. In Kimi Claw, run:"
echo "   browser navigate https://web.telegram.org"
echo ""
echo "2. Login with phone: +6591593838"
echo "3. Enter SMS code when prompted"
echo "4. Navigate to CallistoFX channel"
echo "5. Verify you can see messages"
echo ""

echo "STEP 5: Set Up Cron Jobs"
echo "------------------------"
echo "Add to Kimi Claw cron:"
echo ""
echo "# Every 15 minutes - Dashboard audit"
echo "*/15 * * * * /usr/bin/python3 ~/audit.py"
echo ""
echo "# Every 2 minutes - Telegram monitor"
echo "*/2 * * * * /usr/bin/python3 ~/telegram_monitor.py"
echo ""

echo "STEP 6: Test Integration"
echo "------------------------"
echo "1. Send test message to CHAD_YI:"
echo "   'Kimi-Claw-Helios is online'"
echo ""
echo "2. Wait for CallistoFX signal"
echo "3. Verify alert reaches CHAD_YI"
echo ""

echo "STEP 7: Enable 24/7 Mode"
echo "------------------------"
echo "In Kimi Claw settings:"
echo "- Enable 'Always On'"
echo "- Set auto-restart on crash"
echo ""

echo "=============================================="
echo "Setup Complete!"
echo "=============================================="
echo ""
echo "Kimi-Claw-Helios will now:"
echo "- Monitor dashboard every 15 min"
echo "- Watch CallistoFX every 2 min"
echo "- Alert CHAD_YI immediately"
echo "- Run 24/7 in cloud"
echo ""
echo "Next: Configure message bridge between"
echo "Kimi Claw and CHAD_YI (OpenClaw)"